export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        // ── original aqua palette ──
        aqua: {
          50:  '#EAF7FB',
          100: '#BFEAF2',
          300: '#63C9D6',
          600: '#1E7F8C',
          900: '#20343A',
        },
        // ── NutriPlan design system ──
        primary:                  '#006d40',
        'primary-container':      '#2bb673',
        'primary-fixed':          '#7afbb1',
        'primary-fixed-dim':      '#5cde97',
        'on-primary':             '#ffffff',
        'on-primary-container':   '#004024',
        'on-primary-fixed':       '#002110',
        'on-primary-fixed-variant':'#00522f',
        'inverse-primary':        '#5cde97',

        secondary:                '#006c49',
        'secondary-container':    '#6cf8bb',
        'secondary-fixed':        '#6ffbbe',
        'secondary-fixed-dim':    '#4edea3',
        'on-secondary':           '#ffffff',
        'on-secondary-container': '#00714d',
        'on-secondary-fixed':     '#002113',
        'on-secondary-fixed-variant':'#005236',

        tertiary:                 '#55615a',
        'tertiary-container':     '#96a39b',
        'tertiary-fixed':         '#d9e6dd',
        'tertiary-fixed-dim':     '#bdcac1',
        'on-tertiary':            '#ffffff',
        'on-tertiary-container':  '#2e3a34',
        'on-tertiary-fixed':      '#131e19',
        'on-tertiary-fixed-variant':'#3e4943',

        background:               '#f8f9ff',
        surface:                  '#f8f9ff',
        'surface-dim':            '#cbdbf5',
        'surface-bright':         '#f8f9ff',
        'surface-container':      '#e5eeff',
        'surface-container-low':  '#eff4ff',
        'surface-container-high': '#dce9ff',
        'surface-container-highest':'#d3e4fe',
        'surface-container-lowest':'#ffffff',
        'surface-variant':        '#d3e4fe',
        'surface-tint':           '#006d40',
        'on-background':          '#0b1c30',
        'on-surface':             '#0b1c30',
        'on-surface-variant':     '#3d4a40',
        'inverse-surface':        '#213145',
        'inverse-on-surface':     '#eaf1ff',

        outline:                  '#6d7a6f',
        'outline-variant':        '#bccabd',

        error:                    '#ba1a1a',
        'error-container':        '#ffdad6',
        'on-error':               '#ffffff',
        'on-error-container':     '#93000a',
      },
      borderRadius: {
        sm:  '8px',
        md:  '12px',
        lg:  '16px',
        xl:  '0.75rem',
        full:'9999px',
      },
      fontFamily: {
        'body-lg':        ['Inter', 'sans-serif'],
        'body-md':        ['Inter', 'sans-serif'],
        'label-caps':     ['Lexend', 'sans-serif'],
        'metric-display': ['Lexend', 'sans-serif'],
        h1: ['Plus Jakarta Sans', 'sans-serif'],
        h2: ['Plus Jakarta Sans', 'sans-serif'],
        h3: ['Plus Jakarta Sans', 'sans-serif'],
      },
      fontSize: {
        'body-lg':        ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-md':        ['16px', { lineHeight: '1.5', fontWeight: '400' }],
        'label-caps':     ['12px', { lineHeight: '1.2', letterSpacing: '0.05em', fontWeight: '600' }],
        'metric-display': ['28px', { lineHeight: '1.1', fontWeight: '700' }],
        h3: ['24px', { lineHeight: '1.4', fontWeight: '600' }],
        h2: ['32px', { lineHeight: '1.3', fontWeight: '600' }],
        h1: ['40px', { lineHeight: '1.2', fontWeight: '700' }],
      },
      animation: {
        'fade-up':  'fadeUp 1s cubic-bezier(0.16, 1, 0.3, 1) forwards',
        'fade-in':  'fadeIn 1.2s cubic-bezier(0.16, 1, 0.3, 1) forwards',
        'scale-up': 'scaleUp 1.2s cubic-bezier(0.16, 1, 0.3, 1) forwards',
        float:      'float 6s ease-in-out infinite',
        mesh:       'mesh 15s ease infinite',
      },
      keyframes: {
        fadeUp: {
          '0%':   { opacity: '0', transform: 'translateY(40px) scale(0.98)' },
          '100%': { opacity: '1', transform: 'translateY(0) scale(1)' },
        },
        fadeIn: {
          '0%':   { opacity: '0' },
          '100%': { opacity: '1' },
        },
        scaleUp: {
          '0%':   { opacity: '0', transform: 'scale(0.9)' },
          '100%': { opacity: '1', transform: 'scale(1)' },
        },
        float: {
          '0%, 100%': { transform: 'translateY(0)' },
          '50%':      { transform: 'translateY(-20px)' },
        },
        mesh: {
          '0%':   { backgroundPosition: '0% 50%' },
          '50%':  { backgroundPosition: '100% 50%' },
          '100%': { backgroundPosition: '0% 50%' },
        },
      },
    },
  },
  plugins: [],
};